services:
  wow-crafting-bot:
    image: ghcr.io/lucabucciferro1/craftyourexcuses:latest
    container_name: wow-crafting-bot
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: your-bot-token-here
      DISCORD_GUILD_ID: your-server-id-here
      CRAFTING_DATA_FILE: /data/crafting_data.json
    volumes:
      - /DATA/AppData/wow-crafting-bot/data:/data
